language: ruby
rvm:
- 2.3.3

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: rake deploy

after_success:
  - rsync -az --delete --exclude '.git*' ../_site/ .
  - touch .nojekyll

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch

exclude: [vendor]

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
