# site settings
title: Dulwich Pyschotherapy
subtitle: Dr. Paola Valerio
email: paola@dulwichpsychsotherapy.com
description: Dr Paola Valerio is a jungian analyst offering psychotherapy, therapy, counselling and couples counselling.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
author: Paola Valerio
street_address: 170 Lowden Road
city: London
state: London
zip_code: SE24 0BT
country: United Kingdom
phone: 020 7733 8526

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: null
facebook_url: null
github_url: null
gitlab_url: null
googleplus_url: null
instagram_url: null
linkedin_url: null
pinterest_url: null
slack_url: null
twitter_url: null

# build settings
markdown: kramdown

plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap

assets:
  autowrite: true
  prefix: '/assets'
  digest: true
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
  sass:
    style: nested
    line_numbers: true
    sourcemap: file
  features:
    automatic_img_alt: true
  image_optim:
    zero_png:
      advpng:
        level: 0
      optipng:
        level: 0
      pngout:
        strategy: 4
